# Generated by Django 2.2.1 on 2019-05-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderController',
            fields=[
                ('order_id', models.TextField(primary_key=True, serialize=False)),
                ('customer_id', models.TextField()),
                ('delivery_id', models.TextField()),
                ('order_items', models.TextField()),
                ('destination', models.TextField()),
                ('status', models.BinaryField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
