# Generated by Django 2.1.7 on 2019-05-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchIndex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchindex',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='searchindex',
            table='search_index',
        ),
    ]
